version: '3'
services:
  client:
    image: "avidocker001/multi-client"
    hostname: client
    mem_limit: 128m
  server:
    image: "avidocker001/multi-api"
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  worker:
    image: "avidocker001/multi-worker"
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_PORT=$REDIS_PORT
      - REDIS_HOST=$REDIS_HOST
  nginx:
    image: "avidocker001/multi-nginx"
    mem_limit: 128m
    hostname: nginx
    ports:
      - 80:80